In [5]:
import torch

v = torch.linspace(0, 1e-6, steps=10).requires_grad_()

def bnorm(val):
    n = val.detach().clone().requires_grad_(True)
    c = n.reshape(-1, 1)
    
    nn = c.norm(dim=-1)
    torch.autograd.backward(nn, torch.ones_like(nn))
    return n.grad

def snorm(val):
    n = val.detach().clone().requires_grad_(True)
    c = n.reshape(-1, 1)
    
    nn = (c ** 2).sum(dim=-1).sqrt()
    
    torch.autograd.backward(nn, torch.ones_like(nn))
    return n.grad

print("torch.__version__:")
display(torch.__version__)

print("vals:")
display(v)

print("torch.norm(v, dim=-1) grad:")
display(bnorm(v))

print("(v**2).sum(dim=-1).sqrt() grad:")
display(snorm(v))

torch.__version__:


'1.8.1+cu111'

vals:


tensor([0.0000e+00, 1.1111e-07, 2.2222e-07, 3.3333e-07, 4.4444e-07, 5.5556e-07,
        6.6667e-07, 7.7778e-07, 8.8889e-07, 1.0000e-06], requires_grad=True)

torch.norm(v, dim=-1) grad:


tensor([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(v**2).sum(dim=-1).sqrt() grad:


tensor([nan, 1., 1., 1., 1., 1., 1., 1., 1., 1.])